export DROBO="5n"
export TOOLCHAIN="${BUILD_TOOLCHAIN:-${HOME}/xtools/toolchain/${DROBO}}"
export ARCH="armv7-a"
export HOST="arm-marvell-linux-gnueabi"
export PATH="${TOOLCHAIN}/bin:~/bin:$PATH"
export CFLAGS="-march=${ARCH} -mcpu=marvell-pj4 -mfpu=vfpv3-d16 -mfloat-abi=softfp"
#export CFLAGS="-mcpu=marvell-pj4 -mfpu=vfpv3-d16 -mfloat-abi=softfp"
export CXXFLAGS="${CFLAGS}"
#export CC="${TOOLCHAIN}/bin/${HOST}-gcc"
#export CXX="${TOOLCHAIN}/bin/${HOST}-g++"
#export AR="${TOOLCHAIN}/bin/${HOST}-ar"
#export AS="${TOOLCHAIN}/bin/${HOST}-as"
#export RANLIB="${TOOLCHAIN}/bin/${HOST}-ranlib"
#export STRIP="${TOOLCHAIN}/bin/${HOST}-strip"
export CC="/home/drobo/xtools/toolchain/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc"
export CXX="/home/drobo/xtools/toolchain/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++"
export AR="/home/drobo/xtools/toolchain/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-ar"
export AS="/home/drobo/xtools/toolchain/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-as"
export RANLIB="/home/drobo/xtools/toolchain/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-ranlib"
export STRIP="/home/drobo/xtools/toolchain/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-strip"
export DROBOAPPS="/mnt/DroboFS/Shares/DroboApps"
